const properties=[
{id:1,ref:'LI-001',type:'parcelle',status:'vente',state:'Terrain nu',zone:'Abomey-Calavi',title:'Parcelle résidentielle de 500 m²',price:'18 500 000 FCFA',meta:['500 m²','Zone résidentielle'],desc:'Parcelle destinée à un projet résidentiel. Les informations foncières doivent être vérifiées avant engagement.',image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1000&q=85'},
{id:2,ref:'LI-002',type:'maison',status:'vente',state:'Bon état',zone:'Cotonou',title:'Maison familiale R+1',price:'95 000 000 FCFA',meta:['4 chambres','2 salons'],desc:'Maison familiale avec espaces de vie et dépendances. Visite sur rendez-vous.',image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85'},
{id:3,ref:'LI-003',type:'appartement',status:'location',state:'Neuf',zone:'Cotonou',title:'Appartement moderne',price:'350 000 FCFA / mois',meta:['2 chambres','Meublé'],desc:'Appartement moderne proposé à la location. Conditions à confirmer auprès de l’agence.',image:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=85'},
{id:4,ref:'LI-004',type:'parcelle',status:'vente',state:'Terrain nu',zone:'Comé',title:'Parcelle résidentielle',price:'12 000 000 FCFA',meta:['600 m²','Accès routier'],desc:'Terrain destiné à un projet résidentiel ou d’investissement.',image:'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1000&q=85'},
{id:5,ref:'LI-005',type:'maison',status:'location',state:'Bon état',zone:'Porto-Novo',title:'Maison à louer',price:'250 000 FCFA / mois',meta:['3 chambres','Cour'],desc:'Maison proposée à la location résidentielle.',image:'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=85'},
{id:6,ref:'LI-006',type:'local',status:'location',state:'À rénover',zone:'Ouidah',title:'Local commercial',price:'180 000 FCFA / mois',meta:['80 m²','Axe passant'],desc:'Local pouvant accueillir une activité commerciale, sous réserve de visite et validation.',image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1000&q=85'}
];
const labels={parcelle:'Parcelle',maison:'Maison',appartement:'Appartement',local:'Local commercial',vente:'À vendre',location:'À louer'};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let favorites=JSON.parse(localStorage.getItem('levelImmoFavorites')||'[]'), favMode=false;
function saveFav(){localStorage.setItem('levelImmoFavorites',JSON.stringify(favorites));$('#favCount').textContent=favorites.length}
function toggleFav(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];saveFav();render()}
function render(){
 const key=$('#keyword').value.toLowerCase().trim(), type=$('#filterType').value,status=$('#filterStatus').value,state=$('#filterState').value,zone=$('#filterZone').value;
 let list=properties.filter(p=>(!key||`${p.title} ${p.zone} ${p.ref}`.toLowerCase().includes(key))&&(!type||p.type===type)&&(!status||p.status===status)&&(!state||p.state===state)&&(!zone||p.zone===zone));
 if(favMode)list=list.filter(p=>favorites.includes(p.id));
 $('#resultCount').textContent=`${list.length} bien${list.length>1?'s':''} trouvé${list.length>1?'s':''}`;
 $('#propertyGrid').innerHTML=list.map(p=>`<article class="property"><div class="property-img" style="background-image:url('${p.image}')"><span class="badge">${labels[p.status]}</span><button class="heart ${favorites.includes(p.id)?'active':''}" onclick="toggleFav(${p.id})" aria-label="Favori">${favorites.includes(p.id)?'♥':'♡'}</button></div><div class="property-body"><span class="location">Réf. ${p.ref} • ${p.zone} • ${labels[p.type]}</span><h3>${p.title}</h3><div class="meta">${p.meta.map(x=>`<span class="chip">${x}</span>`).join('')}</div><div class="price">${p.price}</div><div class="property-foot"><span class="state">État : ${p.state}</span><button onclick="showProperty(${p.id})">Voir le bien →</button></div></div></article>`).join('');
 $('#empty').classList.toggle('hidden',list.length>0);saveFav();
}
function showProperty(id){const p=properties.find(x=>x.id===id);$('#propertyDetail').innerHTML=`<div class="detail-grid"><img src="${p.image}" alt="${p.title}"><div class="detail-info"><span class="eyebrow dark">${labels[p.status]} • RÉF. ${p.ref}</span><h2>${p.title}</h2><p class="location">${p.zone} • ${labels[p.type]} • ${p.state}</p><p class="detail-price">${p.price}</p><div class="meta">${p.meta.map(x=>`<span class="chip">${x}</span>`).join('')}</div><p>${p.desc}</p><div class="notice">Les documents, disponibilité, localisation exacte et conditions financières doivent être confirmés par LEVEL-IMMO avant toute transaction.</div><a class="btn primary" href="#contact" onclick="closeModals();prefill('${p.title.replace(/'/g,"\\'")}')">Demander ce bien</a></div></div>`;$('#propertyModal').classList.add('open')}
function prefill(title){$('#contactForm textarea').value=`Bonjour LEVEL-IMMO, je suis intéressé(e) par le bien « ${title} ». Merci de me contacter.`;setTimeout(()=>$('#contact').scrollIntoView({behavior:'smooth'}),50)}
function closeModals(){$$('.modal').forEach(m=>m.classList.remove('open'))}
function applyHero(){ $('#filterType').value=$('#heroType').value;$('#filterStatus').value=$('#heroStatus').value;$('#filterZone').value=$('#heroZone').value;$('#filterState').value='';$('#keyword').value='';favMode=false;render();$('#biens').scrollIntoView({behavior:'smooth'}) }
$('#heroSearch').onclick=applyHero;$$('.quick button').forEach(b=>b.onclick=()=>{const q=b.dataset.q;if(['vente','location'].includes(q)){$('#filterStatus').value=q;$('#filterType').value=''}else{$('#filterType').value=q;$('#filterStatus').value=''}$('#keyword').value='';favMode=false;render();$('#biens').scrollIntoView({behavior:'smooth'})});
['keyword','filterType','filterStatus','filterState','filterZone'].forEach(id=>$('#'+id).addEventListener(id==='keyword'?'input':'change',()=>{favMode=false;render()}));
$('#resetFilters').onclick=()=>{['keyword','filterType','filterStatus','filterState','filterZone'].forEach(id=>$('#'+id).value='');favMode=false;render()};$('#favOnly').onclick=()=>{favMode=!favMode;render()};
$('#openContract').onclick=()=>$('#contractModal').classList.add('open');$('#ownerBtn').onclick=()=>$('#ownerModal').classList.add('open');$$('.close').forEach(x=>x.onclick=closeModals);$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModals()}));
$('#contactForm').onsubmit=e=>{e.preventDefault();$('#formMsg').textContent='Demande enregistrée dans le formulaire. Connectez-le à votre e-mail, WhatsApp ou CRM pour recevoir réellement les messages.'};$('#ownerForm').onsubmit=e=>{e.preventDefault();$('#ownerMsg').textContent='Demande de dépôt enregistrée localement. Une connexion à une base de données permettra ensuite de la transmettre à LEVEL-IMMO.'};
$('#whatsappBtn').href='https://wa.me/22900000000?text='+encodeURIComponent('Bonjour LEVEL-IMMO, je souhaite obtenir des informations sur vos services immobiliers.');
$('.menu').onclick=()=>$('#nav').classList.toggle('open');$('#year').textContent=new Date().getFullYear();render();
